version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka-network
  chat-db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
networks:
  kafka-network:
    driver: bridge
#  auth-service:
#    build: ./path/to/your/auth-service
#    ports:
#      - "8000:8000"
#    depends_on:
#      - chat-db
#      - kafka
#
#  chat-service:
#    build: ./path/to/your/chat-service
#    ports:
#      - "8001:8000"
#    depends_on:
#      - chat-db
#      - kafka
