version: '3'
services:
  chat-db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: chat